# Generated by Django 5.2.7 on 2025-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(unique=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('greeting_name', models.CharField(max_length=255)),
            ],
        ),
    ]
