# Generated by Django 5.2.7 on 2025-10-19 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('diyas_lit', models.IntegerField(default=0)),
                ('total_diyas', models.IntegerField(default=7)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_interactions', to='contact.contact')),
            ],
            options={
                'verbose_name': 'Game Interaction',
                'verbose_name_plural': 'Game Interactions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiyaLightTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diya_number', models.IntegerField()),
                ('lit_at', models.DateTimeField(auto_now_add=True)),
                ('time_from_start', models.FloatField()),
                ('game_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diya_events', to='greetings.gameinteraction')),
            ],
            options={
                'verbose_name': 'Diya Light Event',
                'verbose_name_plural': 'Diya Light Events',
                'ordering': ['lit_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='contact.contact')),
            ],
            options={
                'verbose_name': 'Visit Tracking',
                'verbose_name_plural': 'Visit Trackings',
                'ordering': ['-visited_at'],
            },
        ),
    ]
